from . import rs_poli
from . import rs_grup_diagnosa
from . import rs_diagnosa
from . import res_partner_pasien
from . import rs_jenis_bayar
from . import rs_agama
from . import rs_goldar
from . import rs_kelas
from . import rs_stat_kawin
from . import rs_prosedur