from . import rs_unit
from . import rs_grup_diagnosa
from . import rs_diagnosa
from . import res_partner_pasien
from . import rs_jenis_bayar
from . import rs_agama
from . import rs_goldar
from . import rs_kelas
from . import rs_stat_kawin
from . import rs_prosedur
from . import rs_gender
from . import rs_bed
from . import rs_cara_masuk
from . import rs_asal_rujukan
from . import rs_cara_datang
from . import rs_kamar
from . import rs_ruang
from . import rs_hub_pasien
from . import rs_kun
from . import rs_data_sdm
from . import rs_data_kamar
from . import product_template
